nerdbord/good-dev-hunting-app

src/components/GithubAcc/GithubAcc.tsx, src/components/MyProfileBtn/MyProfileBtn.tsx
- The MyProfile button is now hidden when viewing the user's own profile.
- Navigation to the user's profile via GitHub account button has been implemented using a Link component for a smoother experience.
=> feat: hide MyProfile button on user's profile

package-lock.json, package.json, src/app/moderation/layout.tsx, src/app/moderation/page.tsx, src/app/my-profile/layout.tsx, src/app/my-profile/page.module.scss, src/app/my-profile/page.tsx, src/app/page.tsx, src/app/profiles/layout.tsx, src/app/profiles/page.tsx, src/components/Container/Container.module.scss, src/components/Headers/AppHeader/AppHeader.module.scss, src/components/Logo/Logo.module.scss, src/components/landing-page/Hero/Hero.module.scss, src/components/landing-page/LandingContainer/LandingContainer.module.scss, src/components/landing-page/LandingHeader/LandingHeader.module.scss
bumped TS so we could remove TS expected error + unified containers
=> fix: unify containers + bump TS and types

src/backend/profile/profile.service.ts, src/components/ProfileList/ProfileList.module.scss, src/components/ProfileList/ProfileList.tsx, src/components/landing-page/TalentSection/TalentSection.tsx
- use devtools to find problem, only delete display:flex
=> fix: move 'profile not found' to the left side

src/components/ProfileCard/ProfileCard.tsx, src/data/frontend/profile/mappers.ts
=> fix: small fix, fixed seniority level display with mapSeniorityLevel

src/app/(profile)/(components)/MyProfile/ProfileTopBar/ProfileTopBar.module.scss, src/app/(profile)/my-profile/(components)/ToggleOpenToWork.tsx, src/app/(profile)/my-profile/(components)/ToogleOpenToWork.module.scss, src/components/Button/Button.module.scss, src/components/Switch/Switch.module.scss, src/components/Switch/Switch.tsx, src/components/Tooltip/Tooltip.module.scss
=> feat: tooltip is 1 to 1 figma style now

src/app/(profile)/(components)/UserProfile/UserProfileDetails/UserProfileDetails.module.scss
pre-wrap was missed in user profile bio
=> fix: fixing user profile bio section

src/app/(profile)/(components)/ConnectToNerbordButton/ConnectToNerdbordButton.tsx, src/app/(profile)/(components)/MyProfile/ProfileTopBar/ProfileTopBar.module.scss, src/app/(profile)/(components)/MyProfile/ProfileTopBar/ProfileTopBar.tsx, src/components/Switch/Switch.module.scss
-I added a 'available for work' button at the top of the application in the mobile view.
- I removed the button view on the lower AppHeader in the 'my-profile' tab.
- in place of the removed buttons I added btn nerd conected.
- consulted with Karolina.
=> Fix problem with switch on mobile view

src/app/(auth)/auth.ts, src/backend/github-details/github-details.service.ts, src/backend/user/user.service.ts
Currently logging in was not working as it was trying to overwrite existing unique values
=> fix: auth fix

src/app/(profile)/moderation/(components)/StateStatus/StateStatus.tsx, src/components/TextArea/TextArea.module.scss
I fixed the styles in the MDX composite, they now match the project style.
=> Feat style link insert btn in mdx

src/app/(profile)/(components)/FilterTabs/Tab.tsx, src/app/(profile)/moderation/(components)/StateStatus/StateStatus.tsx, src/app/(profile)/my-profile/(components)/CreateProfile/PersonalInfo/PersonalInfo.module.scss, src/app/(profile)/my-profile/(components)/EditProfileForm/EditProfileForm.tsx, src/components/Button/Button.module.scss, src/components/MarkdownReader/MarkdownReader.module.scss, src/components/TextArea/BioTextArea.tsx, src/components/TextArea/TextArea.module.scss
- fix markdown formatting
- add approve / reject buttons approved / rejected profiles
- adjust mdx editor styling to our design
=> release: fixes

src/app/(auth)/login/(components)/LoginHunter/LoginHunter.tsx, src/app/(auth)/login/page.module.scss, src/app/(profile)/(components)/AppHeader/AppHeader.module.scss, src/app/(profile)/(components)/AppHeader/AppHeader.tsx, src/components/Box/Box.module.scss, src/components/Button/Button.module.scss, src/components/FindTalentsBtn/FindTalentsBtn.tsx, src/components/LoginBtn/LoginBtn.module.scss, src/components/LoginBtn/LoginBtn.tsx, src/components/LoginBtn/LoginBtnsWrapper.tsx, src/components/landing-page/LandingHeader/LandingHeader.module.scss, src/components/landing-page/LandingHeader/LandingHeader.tsx
- The login page has been adjusted for mobile compatibility.
- Redirect buttons to the login page have been added to the landing page.
TODO
- Add login buttons to the /profiles page.
- Implement a confirmation message after successfully joining as a hunter.
=> [Login Page]: Adjust Login Page to mobile

package-lock.json, prisma/migrations/20240220103200_addedn_view_counter_to_profile/migration.sql, prisma/schema.prisma, src/app/(profile)/(components)/MyProfile/ProfileTopBar/ProfileTopBar.module.scss, src/app/(profile)/(components)/MyProfile/ProfileTopBar/ProfileTopBar.tsx, src/app/(profile)/_actions/countProfileView.ts, src/app/(profile)/my-profile/(components)/CreateProfileForm/CreateProfileForm.tsx, src/app/(profile)/my-profile/(components)/EditProfileForm/EditProfileForm.tsx, src/app/(profile)/my-profile/(components)/EditProfileForm/mappers.ts, src/app/(profile)/my-profile/(components)/ProfileViews/ProfileViews.module.scss, src/app/(profile)/my-profile/(components)/ProfileViews/ProfileViews.tsx, src/app/(profile)/my-profile/(components)/ToggleOpenToWork.tsx, src/app/(profile)/my-profile/(components)/ToogleOpenToWork.module.scss, src/app/(profile)/profiles/[username]/page.tsx, src/app/(profile)/profiles/layout.tsx, src/app/(profile)/types.ts, src/assets/icons/ViewIcon.tsx, src/backend/profile/profile.serializer.ts, src/backend/profile/profile.service.ts, src/components/VisitorBanner/VisitorBanner.module.scss, src/components/VisitorBanner/VisitorBanner.tsx, tsconfig.json
Reverts nerdbord/good-dev-hunting-app#241
=> Revert "Revert "Banner UI for unauthorized visitor""

src/app/(profile)/profile.helpers.ts
I modified the logic of the technologyFilter to show only records that meet all selected values, rather than just some of them. Essentially, I changed the filter logic to use "AND" for the selected values in the dropdown, instead of "OR"."
=> fix: change logic in technologyfilter

src/components/Dropdowns/DropdownFilterMulti/DropdownFilterMulti.module.scss, src/components/Dropdowns/DropdownOptionItem/DropdownOptionItem.module.scss
final fixes to activate first checkbox while Clear button is visible
=> fix: final fixes

apps/platform-app/messages/en.json
=> fix: translation bug on signin page

apps/platform-app/src/components/Dropdowns/DropdownFilterMulti/DropdownFilterMulti.module.scss, packages/ui-system/src/components/Dropdowns/DropdownSearchInput/DropdownSearchInput.module.scss
=> fix: search input is sticky now also clear btn is stick under input

apps/platform-app/messages/en.json, apps/platform-app/messages/pl.json, apps/platform-app/src/app/[locale]/(profile)/(components)/UserPhotoUploader/UserPhotoUploader.tsx, apps/platform-app/src/app/[locale]/(profile)/(routes)/my-profile/(components)/CreateProfile/PersonalInfo/PersonalInfo.tsx
- adding info about optional fields in all forms
=> feat: adding info about optional fields in all forms

apps/platform-app/src/app/[locale]/(profile)/_workflows/profile-evaluation.workflow.ts
A notification will be sent to Discord if the agent does not invoke any tool for any reason.
=> added safeguard for missing tool call

apps/platform-app/src/app/[locale]/(profile)/(components)/LocaleSwitcher/LocaleSwitcherSelect.module.scss, apps/platform-app/src/app/[locale]/(profile)/(components)/LocaleSwitcher/LocaleSwitcherSelect.tsx, apps/platform-app/src/app/[locale]/page.module.scss, apps/platform-app/src/components/hunter-landing/HunterHero/HeroBottom/HeroBottom.module.scss, apps/platform-app/src/components/hunter-landing/HunterHero/HeroBottom/HeroBottom.tsx, apps/platform-app/src/components/hunter-landing/HunterHero/HunterHero.module.scss, apps/platform-app/src/components/hunter-landing/HunterHero/TagTooltip/TagTooltip.module.scss, apps/platform-app/src/components/hunter-landing/HunterHero/TextareaHero/TextareaHero.module.scss
=> Fix  UI fixes

apps/platform-app/messages/en.json, apps/platform-app/messages/pl.json, apps/platform-app/next.config.js, apps/platform-app/src/app/[locale]/page.module.scss, apps/platform-app/src/app/globals.scss, apps/platform-app/src/components/hunter-landing/HunterCTA/HunterCTA.tsx, apps/platform-app/src/components/hunter-landing/HunterFAQ/HunterFAQ.tsx, apps/platform-app/src/components/hunter-landing/HunterHero/HeroBottom/HeroBottom.module.scss, apps/platform-app/src/components/hunter-landing/HunterHero/HeroBottom/HeroBottom.tsx, apps/platform-app/src/components/hunter-landing/HunterHero/HunterHero.module.scss, apps/platform-app/src/components/hunter-landing/HunterHero/HunterHero.tsx, apps/platform-app/src/components/hunter-landing/HunterHero/TextareaHero/TextareaHero.module.scss, apps/platform-app/src/components/hunter-landing/HunterHero/TextareaHero/TextareaHero.tsx, apps/platform-app/src/components/hunter-landing/HunterHowItWorks/HunterHowItWorks.module.scss, apps/platform-app/src/components/hunter-landing/HunterHowItWorks/HunterHowItWorks.tsx, apps/platform-app/src/components/hunter-landing/HunterReviews/HunterReviews.module.scss, apps/platform-app/src/components/hunter-landing/HunterReviews/HunterReviews.tsx, apps/platform-app/src/components/hunter-landing/HunterRiskReducers/HunterRiskReducers.tsx, apps/platform-app/src/components/hunter-landing/HunterTeam/TeamMemberCard.module.scss, apps/platform-app/src/components/hunter-landing/HunterTeam/TeamMemberCard.tsx, apps/platform-app/src/components/hunter-landing/HunterTeam/TeamMembersCarousel.tsx, apps/platform-app/src/components/hunter-landing/UI/ReviewCard/ReviewCard.tsx, apps/platform-app/src/components/hunter-landing/UI/TagButton/TagButton.module.scss, apps/platform-app/src/components/hunter-landing/UI/TagButton/TagButton.tsx, apps/platform-app/src/components/hunter-landing/UI/TagsRow/TagsRow.tsx, apps/platform-app/src/i18n/request.ts
Removed the issue causing the Hero tooltip not to display, ensuring tooltips now render correctly.
Also fixed the mobile hydration error.
=> Fix  ios tooltip
